#!/bin/sh
set -ex

export CXX=g++
export AR=ar
export LD=g++
# Reproducibility per AGENTS.md; gen.py appends env CFLAGS/CXXFLAGS/LDFLAGS
# to its own flag set.
export CXXFLAGS="-ffile-prefix-map=$(pwd)=/builddir -gno-record-gcc-switches"
export LDFLAGS="-Wl,--build-id=none"

# gen.py derives the version header from `git describe`; a tarball has no
# .git, so render it from the position/commit forwarded by build.ncl's
# build_args — one source of truth, and the smoketest greps the position
# out of `gn --version`.
mkdir -p out
cat > out/last_commit_position.h <<EOF
// Generated by build/gen.py.

#ifndef OUT_LAST_COMMIT_POSITION_H_
#define OUT_LAST_COMMIT_POSITION_H_

#define LAST_COMMIT_POSITION_NUM $MINIMAL_ARG_POSITION
#define LAST_COMMIT_POSITION "$MINIMAL_ARG_POSITION ($MINIMAL_ARG_COMMIT)"

#endif  // OUT_LAST_COMMIT_POSITION_H_
EOF

# --no-static-libstdc++: link the system libstdc++ (runtime_deps carries
# gcc/libstdcpp) instead of gen.py's static default.
python3 build/gen.py --no-last-commit-position --no-static-libstdc++ --allow-warnings
ninja -C out gn

mkdir -p "$OUTPUT_DIR/usr/bin"
install -m 0755 out/gn "$OUTPUT_DIR/usr/bin/"
