#!/bin/sh
set -ex

./configure --prefix=/usr

# ⚠ HELP TEXT IS OMITTED, DELIBERATELY. Each script is generated by
# generate-help-script.awk from <name>.in, and the awk ALSO reads <name>.txt to
# embed the `--help` / `--manual` output. Those .txt files are produced from
# desc/*.xml by `xmlto txt`, which drags in docbook-xsl and a text browser —
# two packages we do not have, for output that is purely cosmetic. Upstream
# stopped shipping pre-generated tarballs after 1.1.3 (portland.freedesktop.org
# has nothing for 1.2.1), so there is no ready-made source to take instead.
#
# Creating empty .txt stubs makes awk's `getline < txtfile` read nothing. The
# scripts' actual behaviour lives in the .in files and is unaffected; only
# `xdg-open --help` and friends print an empty block. The agentbox image
# overrides /usr/local/bin/xdg-open with its own wrapper regardless, so what
# this package supplies is the rest of the suite.
#
# To restore the help text: package xmlto + docbook-xsl and drop the stub loop.
SCRIPTS="xdg-copy xdg-desktop-icon xdg-desktop-menu xdg-email xdg-file-dialog
         xdg-icon-resource xdg-mime xdg-open xdg-realpath xdg-screensaver
         xdg-settings xdg-su xdg-terminal"

cd scripts
for s in $SCRIPTS; do
  [ -f "$s.txt" ] || : > "$s.txt"
done

# Replicates the Makefile's own `%: %.in %.txt` recipe, minus the xmlto path.
for s in $SCRIPTS; do
  awk -f generate-help-script.awk "$s.in" | sed -e "s/@NAME@/$s/g" > "$s"
  chmod a+x "$s"
done
cd ..

install -d "$OUTPUT_DIR/usr/bin"
for s in $SCRIPTS; do
  if [ ! -s "scripts/$s" ]; then
    echo "xdg-utils: scripts/$s was not generated" >&2
    exit 1
  fi
  # Each script must at least parse — an empty .txt must not have produced a
  # truncated heredoc.
  sh -n "scripts/$s" || { echo "xdg-utils: scripts/$s is not valid shell" >&2; exit 1; }
  install -m 755 "scripts/$s" "$OUTPUT_DIR/usr/bin/$s"
done
