#!/bin/sh
set -ex
export CC=gcc
export LD=gcc
export RUSTFLAGS="-C linker=gcc --remap-path-prefix=$(pwd)=/builddir --remap-path-prefix=$HOME/.cargo=/cargo"

# bat's build/application.rs renders assets/completions/*.in for bash, fish and
# zsh. It writes them to $BAT_ASSETS_GEN_DIR when that is set, falling back to
# $OUT_DIR (target/release/build/bat-<hash>/out) when it is not. Pin it, so the
# install paths below are literal instead of globbing `bat-*` — that wildcard
# can match more than one hash-suffixed directory in a dirty target dir.
# Kept under $(pwd) so the --remap-path-prefix above still covers it.
BAT_ASSETS_GEN_DIR="$(pwd)/gen-assets"
export BAT_ASSETS_GEN_DIR
COMP="$BAT_ASSETS_GEN_DIR/assets/completions"

RUSTONIG_DYNAMIC_LIBONIG=1 cargo build --release

install -D -m 0755 target/release/bat $OUTPUT_DIR/usr/bin/bat

# Shell completions (gominimal/inbox#470). All three are generated by the build
# above; before this, zsh and fish were produced on every build and discarded.
# Upstream names the zsh file bat.zsh; it must land as _bat to be autoloadable.
install -D -m 0644 "$COMP/bat.bash" "$OUTPUT_DIR/usr/share/bash-completion/completions/bat"
install -D -m 0644 "$COMP/bat.fish" "$OUTPUT_DIR/usr/share/fish/vendor_completions.d/bat.fish"
install -D -m 0644 "$COMP/bat.zsh"  "$OUTPUT_DIR/usr/share/zsh/site-functions/_bat"

# Assert content, not just existence: a generator that errors to stdout and
# exits 0 leaves a plausible-looking file, and a bash script written to _bat
# would pass a mere `test -s`.
[ -s "$OUTPUT_DIR/usr/share/bash-completion/completions/bat" ]
[ -s "$OUTPUT_DIR/usr/share/fish/vendor_completions.d/bat.fish" ]
[ -s "$OUTPUT_DIR/usr/share/zsh/site-functions/_bat" ]
head -1 "$OUTPUT_DIR/usr/share/zsh/site-functions/_bat" | grep -qx '#compdef bat'
grep -q 'complete -c' "$OUTPUT_DIR/usr/share/fish/vendor_completions.d/bat.fish"
! grep -qi 'bash completion' "$OUTPUT_DIR/usr/share/fish/vendor_completions.d/bat.fish"
grep -qE 'complete .*(-F|-o) ' "$OUTPUT_DIR/usr/share/bash-completion/completions/bat"
# The templates are rendered, not copied — an unsubstituted {{VAR}} means the
# render silently half-failed.
! grep -q '{{' "$OUTPUT_DIR/usr/share/zsh/site-functions/_bat"
