name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  minimal-check:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space
        uses: endersonmenezes/free-disk-space@v3 # Use @main for latest, @v3 for stable
        with:
            remove_android: true
            remove_dotnet: true
            remove_haskell: true
      - uses: actions/checkout@v6
      - uses: gominimal/check@v1
        with:
            channel: unstable
